Features/events UI
UCMercedACM/Chapter-Website pull request #115
Opened 2021-03-22 04:38 UTC by robokae

# Proposed changes

- Translated the events page UI using HTML, SCSS, and Angular.

## Types of changes

What types of changes does your code introduce to the UC Merced's ACM Chapter Website?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x ] I have read the [CONTRIBUTING](https://github.com/UCMercedACM/Chapter-Website/blob/master/CONTRIBUTING.md) doc
- [ ] Lint and unit tests pass locally with my changes**
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

** Passed the lint test, Jasmine: 6 Success, 2 Fail

## Responsiveness

Check off the different **browsers** and **devices** you have tested on. Note: testing includes Horizontal and Vertical alignments

### Browsers

- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Brave
- [ ] Opera

### Devices

#### Phones

- [ x] Moto G4
- [ x] Galaxy S5
- [ x] Pixel 2
- [ x] Pixel 2 XL
- [ ] iPhone 5/SE
- [x ] iPhone 6/7/8
- [ x] iPhone 6/7/8 Plus
- [ x] iPhone X

#### Tablets

- [x ] iPad
- [ x] iPad Pro

#### Desktops

- [ x] Windows 10
- [ x] MacOSX
- [ ] Ubuntu

## Screenshots

<img width="1552" alt="Screen Shot 2021-03-21 at 9 34 17 PM" src="https://user-images.githubusercontent.com/56232476/111941086-81f0dd00-8a8d-11eb-811a-6eb51b790d24.png">

<img width="1016" alt="Screen Shot 2021-03-21 at 9 34 32 PM" src="https://user-images.githubusercontent.com/56232476/111941092-874e2780-8a8d-11eb-9d4c-7db065f37d57.png">

<img width="777" alt="Screen Shot 2021-03-21 at 9 34 49 PM" src="https://user-images.githubusercontent.com/56232476/111941096-89b08180-8a8d-11eb-9666-7b099c13d9ac.png">

<img width="568" alt="Screen Shot 2021-03-21 at 9 36 13 PM" src="https://user-images.githubusercontent.com/56232476/111941104-8c12db80-8a8d-11eb-984d-0357479a7674.png">

## Further comments

2021-04-04 02:58 UTC, adriandarian commented
You need to pull down the changes from the master branch into your branch to resolve this issue, basically you are missing updated code from the master branch and your branch is now out of date.

![image](https://user-images.githubusercontent.com/23567187/113497245-fa589480-94b6-11eb-9385-5ee6a071a629.png)

2021-04-04 03:20 UTC, adriandarian requested changes
Please double-check that the following commands work locally before we can approve the PR.

1. `yarn test`
2. `yarn e2e`
3. `yarn lint`
4. `yarn build`

Also please remove the package-lock.json, in the README.md it states we support yarn's package manager over npm

2021-04-04 03:20 UTC, adriandarian commented on src/app/app.module.ts
> +import { EventCardComponent } from "./event-card/event-card.component";
This should be placed under the components folder or be a single function in the Events page since it is not a reusable component

2021-04-04 03:20 UTC, adriandarian commented on src/app/event-card/event-card.component.scss
> +$primary-color: #084778;
when you pull the latest changes from the master branch you will notice that there are CSS variables in the styles.scss file which can be used by `var(--color)`. So some of these colors might be repeated.

2021-04-04 03:20 UTC, adriandarian commented on src/app/event-card/event-card.component.scss
> +    font-family: Montserrat, Arial, Helvetica, sans-serif;
```suggestion
    font-family: "Montserrat", sans-serif;
```

2021-04-04 03:20 UTC, adriandarian commented on src/app/pages/events/events.component.scss
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap');
this can be removed cause we declared it in the global styles.scss

2021-04-04 03:20 UTC, adriandarian commented on src/app/pages/events/events.component.html
> +            <div class="app-event-card-container" *ngFor="let event of events; let i = index; first as isFirst; last as isLast">
nice clean angular code

2021-04-04 03:20 UTC, adriandarian commented on src/app/event-card/event-card.component.ts
> +  constructor() { }
you should declare the index in the constructor to set a default property value to it aka `index = 0;`

2021-04-04 03:20 UTC, adriandarian commented on src/app/pages/events/events.component.scss
> +    font-family: $font-regular, Arial, Helvetica, sans-serif;
```suggestion
    font-family: $font-regular, sans-serif;
```

2021-04-04 03:20 UTC, adriandarian commented on src/app/pages/events/events.component.scss
> +* {
should never use the * outside the global stylesheet, bad practice

2021-04-04 03:20 UTC, adriandarian commented on src/app/pages/events/events.component.scss
> +    }
You have the `background-color: _____` defined for each of these up above as well, why not combine the CSS tags instead of redeclaring them below

2021-04-13 05:36 UTC, adriandarian commented
Marking as inactive since last update was over 2 weeks ago.

2021-04-13 05:38 UTC, adriandarian commented
Just remove the inactive label once a commit updating this PR is pushed to the matching branch.

2024-08-31 05:16 UTC, No767 commented
Stale PR

2024-08-31 05:16 UTC, closed without merging